# Generated by Django 4.2.2 on 2023-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=200, unique=True, verbose_name='nombre clave')),
                ('name', models.CharField(max_length=200, verbose_name='Red social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
            ],
            options={
                'verbose_name': 'enlace',
                'verbose_name_plural': 'enales',
                'ordering': ['name'],
            },
        ),
    ]
